#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a custom 404 page with the string "Ceci n'est pas une page"

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting nginx service
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating a custom 404 page with the string "Ceci n'est pas une page"
echo -e "<html><head><title>404 Not Found</title></head><body><h1>404 Not Found</h1><p>Ceci n'est pas une page</p></body></html>" > /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sudo tee /etc/nginx/sites-available/custom-404 <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Enable the custom 404 site and disable the default site
sudo ln -s /etc/nginx/sites-available/custom-404 /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
