#!/usr/bin/env bash
# Fixes nginx server that won't shut off via daemon manager
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx stop
pkill nginx
service nginx start

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

service nginx restart

# Check if Nginx is running and listening on port 80
if sudo netstat -tuln | grep -q ':80 '; then
    echo "Nginx is running and listening on port 80."
else
    echo "Nginx is not running or not listening on port 80."
fi