#!/usr/bin/env bash
# Fixes nginx server that won't shut off via daemon manager
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
