#!/usr/bin/env bash

# Install Nginx if not already installed
command -v nginx >/dev/null 2>&1 || { apt-get update && apt-get install nginx -y; }

# Ensure Nginx is listening on port 80
[[ $(sudo netstat -tuln | grep ":80 ") ]] || { sudo tee /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
sudo nginx -t && sudo systemctl reload nginx; }
