#!/usr/bin/env bash
# script to fixes nginx server that won't shut off via daemon manager
# Configures server to listen on port 80 of all server's active IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
