#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd.
# Your script should only display:
# username, user id
# Home directory path for the user
# using while loop

while IFS=: read -r username _ userid _ _ home _
do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home"
    echo
done < /etc/passwd
