#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username _ userid groupid _ home shell
do
    userinfo=$(grep "^$username:" /etc/passwd)
    uid_info=$(awk -F: '{print $5}' <<< "$userinfo")
    password=$(grep "^$username:" /etc/shadow | awk -F: '{print $2}')

    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $uid_info"
done < /etc/passwd
