#!/usr/bin/env bash
# script that groups visitors by IP and HTTP status code, and displays this data.

awk '{ count[$1" "$9]++ } END { for (key in count) print count[key], key }' apache-access.log |
sort -rn -k1,1 |
awk '{printf "%d %s\n", $1, $2, $3}'
