#!/usr/bin/env bash
# This scripts prints Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line. use while and if

i=1
num=9

while [ $i -le 10 ]
do
  echo "Best School"
  if [ $i == $num ]
  then
    echo "Hi"
  fi
  i=$((i+1))
done
