#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
# using while loop

h=0
min=1

while [ $h -le 12 ]
do
    echo "Hour: $h"
    while [ $min -le 59 ]
    do
        echo "$min"
        min=$((min+1))
    done
    min=1
    h=$((h+1))
done
