#!/usr/bin/env bash
# This script displays
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
# using for loop

for i in *
do
    basename "$i" | cut -d '-' -f 2
done
